name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install C/C++ CI
      run: sudo apt-get -y install C/C++ CI
    - name: C/C++ CI code
      run: C/C++ CI M1-Game-Sankemini
 

